name: Nuget

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 #v3.0.0

    - uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 #v4.0

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build the application
      run: msbuild /p:Configuration=Release

    - name: Depoly to Nuget
      run: |
           $package = Get-ChildItem -Recurse -Filter *.nupkg
           nuget push $package $env:nuget_api_key -src https://nuget.org
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
