name: Nuget

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build the application
        run: msbuild /p:Configuration=Release

      - name: Depoly to Nuget
        run: |
          $package = Get-ChildItem -Recurse -Filter *.nupkg
          nuget push $package $env:nuget_api_key -src https://nuget.org
        env:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
