name: Nuget

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce #v2

    - uses: NuGet/setup-nuget@323ab0502cd38fdc493335025a96c8fdb0edc71f #v2.0.1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build the application
      run: msbuild /p:Configuration=Release

    - name: Depoly to Nuget
      run: |
           $package = Get-ChildItem -Recurse -Filter *.nupkg
           nuget push $package $env:nuget_api_key -src https://nuget.org
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
